### ISSUE TITLE
Practica Architect

### ISSUE THREAD

**Issue by Kevinaleatorio** [SistemasTecTlaxiaco/practica-architect-Kevinaleatorio#1]
[Practica Architect.pdf](https://github.com/SistemasTecTlaxiaco/practica-architect-Kevinaleatorio/files/7165746/Practica.Architect.pdf)

**Comment by Brenda-SaM** [comment]
calificación: 17
brenda santos

**Comment by josealfredo79** [comment]
esta practica esta incompleta, no detalla el procedimiento

**Comment by josealfredo79** [comment]
Para la próxima no se revisa por favor.

**Comment by josealfredo79** [comment]
Revisado.
